version: '3.8'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shoppingCartDB
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    ports:
      - "3310:3306"
    networks:
      - dark-scorpion
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  dark-scorpion:

volumes:
  mysql-data:
